# Generated by Django 6.0.2 on 2026-02-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Drama', 'Drama'), ('Horror', 'Horror')], default='Action', max_length=100),
        ),
    ]
